spring.application.name=rrhh_1604961

# CONEXIÓN A POSTGRESQL
# Formato: jdbc:postgresql://[host]:[puerto]/[nombre_bd]
spring.datasource.url=jdbc:postgresql://localhost:5432/recursos_humanos_db
spring.datasource.username=postgres
spring.datasource.password=jesus1213

# El driver cambia para Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Dialecto específico para Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect